[package]
name = "tf-example"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
	"crates/docker"
]

[dependencies]
docker = { version = "0.1.0", path = "crates/docker" }
tf-bindgen = { git = "https://github.com/robert-oleynik/tf-bindgen.git", version = "0.1.0" }
